### ISSUE TITLE
申請加入（限定已經被選為網站組組員的）

### ISSUE THREAD

**Issue by maxchu2021** [PHPConf-TW/website-2015#1]

**Comment by bificoo** [comment]
我要加入，謝謝～

**Comment by hayasilin** [comment]
要加入~謝謝

**Comment by appleboy** [comment]
@bificoo @hayasilin send invitation email

**Comment by Walile** [comment]
這次請略過我。感謝！ :)

Regards,

小哇

2015-06-16 11:27 GMT+08:00 Bo-Yi Wu notifications@github.com:

**Comment by jaceju** [comment]
請略過我吧，這次抽不出時間幫忙了 Orz

**Comment by appleboy** [comment]
- KeaNy
- sakilu / 張匡瑋
- 曾彥淇
- tinda
- 慈恩 
- appleboy 
- 冠緯
- 阮韞澂 
- wanchia

以上是 2015 成員 ....

**Comment by WanchiaTsai** [comment]
我要加入，謝謝～

**Comment by sakilu** [comment]
我要加入，謝謝～

**Comment by gn02158263** [comment]
我要加入，謝謝！
gn02158263@gmail.com

**Comment by tinda** [comment]
你好 我是 tinda :D 我要加入，謝謝！

**Comment by appleboy** [comment]
以上可以留下 email 嗎？這樣我才可以發邀請信加入 slack 群組

**Comment by ryans610** [comment]
你好 我是阮韞澂 我要加入 謝謝~

**Comment by hayasilin** [comment]
請問slack群組邀請信已經發了嗎？(已補上我的E-mail至hackpad)

**Comment by appleboy** [comment]
@hayasilin 我有寄信了 slack，你沒收到嗎？

**Comment by hayasilin** [comment]
@appleboy 我收到信了，已經加入slack了喔，謝謝～名稱是kuan-wei

**Comment by appleboy** [comment]
目前已經招募結束
