### ISSUE TITLE
Sponsors 模組轉移

### ISSUE THREAD

**Issue by appleboy** [PHPConf-TW/website-2015#11]
http://phpconf-tw.github.io/website-2014/#sponsors-section

**Comment by hane1818** [comment]
我想接這個._./

**Comment by hane1818** [comment]
想問一下，可以直接commit上來，還是要fork之後完成再丟pull request過來呢??

**Comment by appleboy** [comment]
先發 PR 看看，如果沒問題就 merge。

**Comment by hane1818** [comment]
那所以要fork嗎OAO??

因為想說collaborator好像可以不用fork就可以在原來的repo 開branch直接做OAO

**Comment by appleboy** [comment]
不用 fork，你直接開 branch 做完可以直接發 PR 喔。

**Comment by hane1818** [comment]
好的，了解，感謝~

**Comment by appleboy** [comment]
Closed via #13
