### ISSUE TITLE
文案更新和校正

### ISSUE THREAD

**Issue by maxchu2021** [PHPConf-TW/website-2015#16]
其他組別會協助提供文案的部分，會陸續提供資料，需要有人協助更新文案，負責接受文案的信件或是訊息後更新到網站上。
- [x] 首頁
- [x] 報名
- [x] 展望
- [x] 講師
- [x] 議程
- [x] 地點
- [x] 贊助 
- [x] 關於

資料來源：

講師
https://docs.google.com/spreadsheets/d/1OPkniRST3BmAgk9QVhgflpAPFN9BZfgf3LJmaHCP7IU/edit#gid=1555242826

議程
https://docs.google.com/document/d/1ZvG8oWQJC0SpZeh269fflS7K3HB-Tvmv1p6bX-iAK-0/edit

贊助
https://drive.google.com/drive/folders/0B-59_4gDCY8XfkQ5X0ZYU1A2bE1YZjNlOGNkbGhMeVRONThNQlptOWpscjBDVDY5NHZrVGc

工作人員
https://docs.google.com/spreadsheets/d/1GKTKejHw2Xwy2Ea_aHH_qrqbE6hsv7XeNglmouw85UQ/edit#gid=0

**Comment by WanchiaTsai** [comment]
i can take it~

**Comment by bificoo** [comment]
報名的區塊想要有1, 2行文案在標題下方，可以讓畫面平衡一點～

**Comment by WanchiaTsai** [comment]
@keanyc  工作人員文件缺總召和法律顧問，要問誰呢？

**Comment by WanchiaTsai** [comment]
@keanyc  講者介紹  和 地點 目前都還沒有資料喔

**Comment by maxchu2021** [comment]
@WanchiaTsai 有幫你要讀取權限了，看有沒有收到，地點的部分和去年一樣。

**Comment by maxchu2021** [comment]
@WanchiaTsai 總召是Firch Tsai，法律顧問確認中。

**Comment by maxchu2021** [comment]
法律顧問一樣是強哥

**Comment by WanchiaTsai** [comment]
@keanyc  thank you~

**Comment by tinda** [comment]
還有需要幫忙得嗎 ?

**Comment by maxchu2021** [comment]
@tinda 都處理好囉，謝謝。
