### ISSUE TITLE
Prospect 展望的照片加入自動換照片的 js

### ISSUE THREAD

**Issue by bificoo** [PHPConf-TW/website-2015#19]
預設三張照片就好，目前只放了一張（三張的 size 要一樣），
照片下面的點點也要跟著換～可以在照片上加 active 的 class，
最後在用 css 設定特效（我可以設定特效）。

**Comment by sakilu** [comment]
幫放了三張圖片 也加了按了點點會在照片(img tag)上放active class的效果
請協助改css了～！ 目前三張圖片都沒設隱藏跟特效
