### ISSUE TITLE
Location 地點圖如何修正

### ISSUE THREAD

**Issue by bificoo** [PHPConf-TW/website-2015#21]
地點圖本來是直的長方形，現在是橫的長方形，看是要重新截圖（結橫的），還是要用 google api 抓地圖進來。

**Comment by gn02158263** [comment]
那我幫忙加GOOGLE MAP上去!

**Comment by gn02158263** [comment]
OK了 目前就靜態圖片 加上標記點 
為了讓參加者容易找到會場入口 我標記點就標在那!
有什麼需要調整的在跟我說

**Comment by appleboy** [comment]
@gn02158263 方便調整為 google map api 也就是嵌入 iframe 模式，讓使用者方便縮放

**Comment by gn02158263** [comment]
好，沒問題!

**Comment by bificoo** [comment]
還需要將 index.html 中的 js 轉至 location 模組中～
