### ISSUE TITLE
講者的 lightbox 套程式

### ISSUE THREAD

**Issue by bificoo** [PHPConf-TW/website-2015#29]
講者 ( Speaker ) 的 lightbox 在 index.jsx 中有新增一塊 SpeakerBox，樣式已經設定好，但是需要根據點擊的講者顯示內容。

**Comment by bificoo** [comment]
.speaker-box-wrapper 為整個 box 的區塊，點擊講者顯示 box ，點擊 box 上的叉叉關閉 box。

**Comment by sakilu** [comment]
已加入js功能,  但是滑鼠移過去不會有手指能顯示可以點 css要麻煩調一下 =v=
