### ISSUE TITLE
工作人員，紀錄組圖示更換

### ISSUE THREAD

**Issue by PetiteDan** [PHPConf-TW/website-2015#30]
因紀錄組主要是負責會場靜態照片攝影
所以希望可將圖示 logo 更換為相機圖案，感謝

紀錄組 丹丹

**Comment by maxchu2021** [comment]
https://github.com/PHPConf-TW/website-2015/commit/f6a2fdce56a95cb10875564ae1fbe7c818f84037 有一併處理了
