### ISSUE TITLE
Firefox 的講者沒有六角形，似乎是 react 不支援 clipPathUnits 屬性？

### ISSUE THREAD

**Issue by bificoo** [PHPConf-TW/website-2015#41]
如果還是無法顯示 svg 的 clipPathUnits 屬性，就考慮直接用正方形了，。

**Comment by maxchu2021** [comment]
正方形也很ok啊。

**Comment by appleboy** [comment]
firefox 的確不支援

https://css-tricks.com/clipping-masking-css/ 

這網頁在 firefox 底下很多圖都爛掉，不然就是不變

先暫時用正方形，看起來也不賴
