### ISSUE TITLE
box 旁邊的 overflow css 問題

### ISSUE THREAD

**Issue by appleboy** [PHPConf-TW/website-2015#42]
![phpconf taiwan 2015](https://cloud.githubusercontent.com/assets/21979/9250304/7bc5408e-41fe-11e5-92e4-5fa5635e62d0.png)

參考這圖

**Comment by bificoo** [comment]
有人可以幫忙測試一下～修正了嗎？

**Comment by appleboy** [comment]
@bificoo fixed
