### ISSUE TITLE
版型設計

### ISSUE THREAD

**Issue by maxchu2021** [PHPConf-TW/website-2015#5]
桌機版
- [x] 選單
- [x] 首頁
- [x] 報名
- [x] 展望
- [x] 講師
- [x] 議程
- [x] 地點
- [x] 贊助
- [x] 關於
- [x] 頁尾

手機版
- [x] 選單
- [x] 首頁
- [x] 報名
- [x] 展望
- [x] 講師
- [x] 議程
- [x] 地點
- [x] 贊助
- [x] 關於
- [x] 頁尾

**Comment by maxchu2021** [comment]
參考網站: 
www.quakecon.org
www.mongodb.org

**Comment by maxchu2021** [comment]
- 放上了Logo(好像還是draft)。
- 修改了配色。
- 修改了選單的UI/UX，滑到下方時會置頂並將Logo隱藏。
- 加上了點選選單項目會移動到所屬區塊(同2014)。
- 講者的圖改成假圖。
- 補上了贊助廠商的圖。

@appleboy 麻煩幫我將main.js相關程式打包處理一下，謝謝。

**Comment by maxchu2021** [comment]
配色參考 http://www.templatemonster.com/demo/42139.html

**Comment by appleboy** [comment]
@keanyc main.js 我來處理

**Comment by appleboy** [comment]
@keanyc 已經處理好 main.js 了。

**Comment by maxchu2021** [comment]
@appleboy :+1:

**Comment by maxchu2021** [comment]
版面設計算是完成了，剩下應該就是微調，再分其他issue來處理吧。
