### ISSUE TITLE
關於新增線路組

### ISSUE THREAD

**Issue by maxchu2021** [PHPConf-TW/website-2015#50]
請找個適合的圖示，謝謝。

**Comment by bificoo** [comment]
加上線路 icon，另外組長名稱不要加上連結，樣式會跑掉。

**Comment by maxchu2021** [comment]
可以把連結加上，修改樣式嗎？

**Comment by maxchu2021** [comment]
Closed by https://github.com/PHPConf-TW/website-2015/commit/df4f32443ad40ce950bdd9946ff7c3ca5b28db70
