### ISSUE TITLE
關於媒體的文宣

### ISSUE THREAD

**Issue by wake** [PHPConf-TW/website-2015#54]
Hi dears，因為今年的媒體合作內容包含了 `百字文宣` 的曝光，所以想問一下這部份有可能排的上去嗎？

不好意思忘記先和網路組 / 設計組確認這部份了，希望不會造成很大困擾 :scream: 真的很抱歉

**Comment by maxchu2021** [comment]
放logo很ok啊，文宣放上去怪怪的。

**Comment by phpconf-taiwan** [comment]
可以做成像講者那樣，只露出一點，點擊了再展開嗎？
2015/9/5 上午9:12於 "KeaNy" notifications@github.com寫道：

**Comment by maxchu2021** [comment]
Closed by https://github.com/PHPConf-TW/website-2015/commit/a70c16809dc1551c4e78491e0f3291c53b1e3076
先改了一個版本，logo下方顯示一行，滑鼠過去會顯示全文，手機則是直接顯示全文，如果有必要的話就再修改囉。
